[package]
name = "mpv"
version = "0.0.2"
authors = ["Cobrand <cobrandw@gmail.com>","yamakaky"]

[dependencies]
log = "0.3"
enum_primitive = "0.1.0"
num = "0.1.32"

[dev-dependencies]
sdl2 = "0.16"
sdl2-sys = "0.8"
